DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS game;
DROP TABLE IF EXISTS match;
DROP TABLE IF EXISTS joined;
DROP TABLE IF EXISTS bet;


CREATE TABLE user
(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL UNIQUE,
  password TEXT NOT NULL
);

CREATE TABLE game
(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  game_id INTEGER UNIQUE NOT NULL,
  creator INTEGER NOT NULL,
  owner_bet BOOLEAN NOT NULL,
  lock_state BOOLEAN NOT NULL
);

CREATE TABLE joined
(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  game_id INTEGER NOT NULL,
  player INTEGER NOT NULL,
  bet BOOLEAN NOT NULL
);

CREATE TABLE match
(
  id INTEGER PRIMARY KEY,
  match_id TEXT NOT NULL,
  game_id INTEGER NOT NULL,
  home FLOAT,
  tie FLOAT,
  away FLOAT
);

CREATE TABLE bet
(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  game_id INTEGER NOT NULL,
  match_id INTEGER NOT NULL,
  player INTEGER NOT NULL,
  prediction FLOAT
);