DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS game;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL UNIQUE,
  password TEXT NOT NULL
);

CREATE TABLE game (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  creator TEXT NOT NULL
);

CREATE TABLE match
(
  id INTEGER PRIMARY KEY,
  matchId TEXT NOT NULL,
  FOREIGN KEY (id) REFERENCES game (id)
);
